services:
  database:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ragezone
      MYSQL_DATABASE: XiuzSource
    volumes:
      - ./XiuzSource/SQL/XiuzSource.sql:/docker-entrypoint-initdb.d/XiuzSource.sql
    ports:
      - 3306:3306