services:
  database:
    image: mysql:5.7.38
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ragezone
      MYSQL_DATABASE: XiuzSource
    volumes:
      - ./SQL/XiuzSource.sql:/docker-entrypoint-initdb.d/XiuzSource.sql
      - v62-mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
  worldserver:
    image: openjdk:7
    volumes:
      - .:/XiuzSource
    working_dir: /XiuzSource
    command: ./launch_world.sh
    depends_on:
      - database

volumes:
  v62-mysql-data: