services:
  worldserver:
    image: openjdk:7
    volumes:
      - .:/v62
    working_dir: /v62
    command: ./launch_world.sh

  channelserver:
    image: openjdk:7
    volumes:
      - .:/v62
    working_dir: /v62
    command: ./launch_channel.sh
    ports:
      - 7575:7575
      - 7576:7576
    depends_on:
      - worldserver

  loginserver:
    image: openjdk:7
    volumes:
      - .:/v62
    working_dir: /v62
    command: ./launch_login.sh
    ports:
      - 8484:8484
    depends_on:
      - worldserver       
