services:
  database:
    image: mysql:5.7.38
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ragezone
      MYSQL_DATABASE: XiuzSource
    volumes:
      - ./XiuzSource.sql:/docker-entrypoint-initdb.d/XiuzSource.sql
      - v62-mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
volumes:
  v62-mysql-data: